name: NoobProtector
main: fromgate.noobprotector.NoobProtector
version: 0.0.2
website: http://www.minecraft-mccity.ru
author: fromgate, fromgate@gmail.com
softdepend: [Vault,Towny]
commands:
   noob:
      aliases: [pvp]
      description: 
      usage: 
           /noob help
   pvp-on:
      aliases: [pvpon]
      description: 
      usage: 
           /pvp-on
          